//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PretplatniciDA.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PretplatniciEntities : DbContext
    {
        public PretplatniciEntities()
            : base("name=PretplatniciEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pretplatnici> Pretplatnici { get; set; }
        public virtual DbSet<StrucnaSprema> StrucnaSprema { get; set; }
    
        public virtual ObjectResult<usp_KorisniciSelectById_Result> usp_KorisniciSelectById(Nullable<int> pretplatnikID)
        {
            var pretplatnikIDParameter = pretplatnikID.HasValue ?
                new ObjectParameter("PretplatnikID", pretplatnikID) :
                new ObjectParameter("PretplatnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_KorisniciSelectById_Result>("usp_KorisniciSelectById", pretplatnikIDParameter);
        }
    
        public virtual int usp_PretplatniciInsert(string ime, string prezime, string email, string lozinka, string korisnickoIme, Nullable<bool> aktivan, Nullable<int> strucnaSpremaID, byte[] slika, byte[] cv)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var aktivanParameter = aktivan.HasValue ?
                new ObjectParameter("Aktivan", aktivan) :
                new ObjectParameter("Aktivan", typeof(bool));
    
            var strucnaSpremaIDParameter = strucnaSpremaID.HasValue ?
                new ObjectParameter("StrucnaSpremaID", strucnaSpremaID) :
                new ObjectParameter("StrucnaSpremaID", typeof(int));
    
            var slikaParameter = slika != null ?
                new ObjectParameter("Slika", slika) :
                new ObjectParameter("Slika", typeof(byte[]));
    
            var cvParameter = cv != null ?
                new ObjectParameter("Cv", cv) :
                new ObjectParameter("Cv", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PretplatniciInsert", imeParameter, prezimeParameter, emailParameter, lozinkaParameter, korisnickoImeParameter, aktivanParameter, strucnaSpremaIDParameter, slikaParameter, cvParameter);
        }
    
        public virtual ObjectResult<usp_PretplatniciSlelectByKorisnickoImeLozinka_Result> usp_PretplatniciSlelectByKorisnickoImeLozinka(string korisnickoIme, string lozinka)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PretplatniciSlelectByKorisnickoImeLozinka_Result>("usp_PretplatniciSlelectByKorisnickoImeLozinka", korisnickoImeParameter, lozinkaParameter);
        }
    
        public virtual ObjectResult<StrucnaSprema> usp_StrucneSpremeSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StrucnaSprema>("usp_StrucneSpremeSelectAll");
        }
    
        public virtual ObjectResult<StrucnaSprema> usp_StrucneSpremeSelectAll(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StrucnaSprema>("usp_StrucneSpremeSelectAll", mergeOption);
        }
    }
}
